services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    ports:
      - 8085:8085
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/appdata/gluetun:/gluetun
    environment:
      - VPN_TYPE=wireguard
      - VPN_SERVICE_PROVIDER=protonvpn
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=Romania
      - TZ=Europe/Belgrade
      - UPDATER_PERIOD=24h
      - UPDATE_VPN_SERVICE_PROVIDERS=protonvpn
      - WIREGUARD_MTU=1100
    dns:
      - 1.1.1.1
      - 1.0.0.1
    labels:
      - com.centurylinklabs.watchtower.enable=true
    devices:
      - /dev/net/tun:/dev/net/tun

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade
      - WEBUI_PORT=8085
    volumes:
      - /mnt/appdata/qbittorrent:/config
      - /mnt/media/torrents:/mnt/media/torrents
    labels:
      - com.centurylinklabs.watchtower.enable=true
    depends_on:
      - gluetun
